### PR TITLE
Refactored a few more Pushjets to Pushfish.

### PR DESCRIPTION
**Pull request by nish-d**
Closing issue (#7 )
Sorry for missing out a few `Pushjets`. 
I have left `https://api.pushjet.io` as is.

### CODE REVIEW

**Comment by VoliKoN** [comment]
Thanks!
Can you please replace `https://api.pushjet.io` to `https://api.push.fish`?

Also you're more than welcome to join our slack!

**Comment by VoliKoN** [comment]
OK, I've tested this on:
https://gitlab.com/PushFish/PushFish-Android/pipelines/34341792
Next time make sure your branch is not stalling behind master, as it's caused us some trouble...
I'm going to merge this and fix the url later...

**Comment by Leopere** [comment]
Thanks again @nish-d @VoliKoN

**Comment by nish-d** [comment]
Yes! I have joined your slack channel. 
Sorry for the trouble, has been one of my first PRs. Will keep my fork updated. Should I change the url and the directory name too?

**Comment by Leopere** [comment]
I wouldn't think that it was trouble, if developers along with humans were perfect we wouldn't need issue trackers.

**Pull request merged**
